### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by PrometheusDante** [AIFSH/ComfyUI-RVC#2]
Hello there, I got the following error when starting comfyui:

> !!!RVC path was added to D:\VER_13\_AI\ComfyUI\python_embeded\lib\site-packages/users.pth
>  if meet `No module` error,try `python main.py` again
> !!!RVC use cache models,make sure your 'assets' complete
> Loading faiss with AVX2 support.
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
> Successfully loaded faiss with AVX2 support.
> Traceback (most recent call last):
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\nodes.py", line 1879, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-RVC\__init__.py", line 40, in <module>
>     from .nodes import LoadAudio, PreViewAudio,RVC_Train,RVC_Infer,CombineAudio
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-RVC\nodes.py", line 9, in <module>
>     from .rvc.train import vc,gpus,default_batch_size,preprocess_dataset,extract_f0_feature,train1key
>   File "D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-RVC\rvc\train.py", line 9, in <module>
>     import fairseq
> ModuleNotFoundError: No module named 'fairseq'
> 
> Cannot import D:\VER_13\_AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-RVC module for custom nodes: No module named 'fairseq'

I've installed through the comfyui manager first, then I tried `pip install -r requirements.txt` from within the `ComfyUI-RVC` folder, which worked without problems, but on starting up comfyui again I get the same error, despite fairseq seemingly correctly installed located in `\custom_nodes\ComfyUI-RVC\venv\Lib\site-packages\fairseq`

I've also seen this line of course:
>  if meet `No module` error,try `python main.py` again

But I don't know what to do with it. 

Thank you for your help and efforts!

**Comment by seyedaed** [comment]
You need to install fairseq.  

python -m pip install git+https://github.com/facebookresearch/fairseq@main

You can also try compiling it from source with instructions here.
https://github.com/facebookresearch/fairseq

Just note if you're using windows without WSL you might have more issues. I had to go another route because of this.

**Comment by aleatorydialogue** [comment]
did you ever figure this out for windows or is it not doable as it is? I don't want to do new comfy install for wsl2....
